# Generated by Django 5.2.7 on 2025-12-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='baby_photos/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('protein', 'Protein'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('other', 'Other')], default='other', max_length=20)),
                ('is_allergen', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meal_photos/')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='blw.baby')),
                ('foods', models.ManyToManyField(blank=True, related_name='meals', to='blw.food')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('rash', 'Rash'), ('hives', 'Hives'), ('vomiting', 'Vomiting'), ('diarrhea', 'Diarrhea'), ('swelling', 'Swelling'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1 (mild) – 5 (severe)')),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blw.baby')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blw.food')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
